common:
    arch: resnet56
    workers: 1
    batch_size: 128
    epochs: 400
    policy: "step"
    base_lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/resnetDW-56
