common:
    arch: resnext29_16_64
    workers: 1
    batch_size: 32
    epochs: 300
    policy: "step"
    base_lr: 0.1 
    momentum: 0.9
    weight_decay: 0.0005
    print_freq: 10
    save_path: checkpoints/resnextDW29_16_64
